name: Android Build

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/android-build.yml'

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run tests
      run: npm test

    - name: Debug - List Android Directory
      run: ls -la android/

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build Android Release
      run: |
        cd android
        ./gradlew assembleRelease --info
      
    - name: Debug - Verify Output Directories
      run: |
        echo "Checking if output directories exist:"
        ls -la android/app/build || echo "build directory doesn't exist"
        ls -la android/app/build/outputs || echo "outputs directory doesn't exist"
        ls -la android/app/build/outputs/apk || echo "apk directory doesn't exist"
        ls -la android/app/build/outputs/apk/release || echo "release directory doesn't exist"
        find android -name "*.apk"
      
    - name: Upload APK (if found)
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: frontend/android/app/build/outputs/apk/release/*.apk
        if-no-files-found: warn  # This will warn instead of failing if no files are found